# Generated by Django 5.1 on 2024-08-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
