# Generated by Django 5.1 on 2024-08-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='kfjf', unique=True),
            preserve_default=False,
        ),
    ]
